#server:
#  port: 8095
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:???/eureka/
#  instance:
#    instance-id: gateway-service-instance
#    hostname: localhost
#spring:
#  application:
#    name: gateway-service