server:
  port: 8093
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/
  instance:
    instance-id: currency-exchanger-service-instance
    hostname: cloud-feignorder-consume
spring:
  application:
    name: currency-exchanger-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/currencyExchange
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    circuitBreakerAspectOrder: 1
    instances:
      limits-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 20
        waitDurationInOpenState: 50s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  retry:
    retryAspectOrder: 2
    instances:
      limits-service:
        maxAttempts: 3
        waitDuration: 10s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException